### ISSUE TITLE
Phone Number and Email Duplicate

### ISSUE THREAD

**Issue by fazilmuammar** [agnostic-apollo/Contacts#1]
why if i add one phone number and one email and then in contact view my phone number and my email duplicate ?

**Comment by agnostic-apollo** [comment]
fixed

**Comment by fazilmuammar** [comment]
Hi sir, can i ask something? i am learning about how to save multiple
edittext to sqlite, it's like add phone number in ur app. do you
have reference how can i make multiple edittext and then save to sqlite
just simple like that sir ? Thank You...

**Comment by agnostic-apollo** [comment]
maybe the following links should help you to add edit texts dynamically...

you can also check the Contact EditFragment's addPhoneEditText() function
in which edittexts are added to the "edit_contact_phones_list"
linearlayout defined in "fragment_contact_edit.xml".

"mPhones" is the list of dynamically added edit texts and "phones" is the
list in which to store the phone number strings the user enters or are
displayed...
When edittext is edited you need to update the correct phones list
item...if you are editing edittext(2), then phones(2) should be updated,
for that you also need to assign each edittext an id with
setId()..When PhoneTextWatcher is called which is the edittext's
textchangelistener you get the id of the edittext with getId() and then
update the phone string of the correct item in the phones list...

for creating and adding sqlite databases there are alot of guides available
online...my code is mostly based on the book i sent, everything is
explained in it in detail...



https://androiddesk.wordpress.com/tag/dynamic-views-in-android-with-an-example/

https://nelsoncvjr.wordpress.com/2013/05/12/addremove-layout-dynamically-on-android/amp/

https://stackoverflow.com/questions/4203506/how-to-add-a-textview-to-a-linearlayout-dynamically-in-android

https://www.myandroidsolutions.com/2013/02/10/android-add-views-into-view-dynamically/amp/

https://medium.com/@uddishverma22/creating-dynamic-layouts-in-android-d4008b72f2d

**Comment by fazilmuammar** [comment]
Thank you sir for the answer, but now  i am learning sqlite with room
database so i'm very confused how to make list edit text when i click add
button sir

**Comment by agnostic-apollo** [comment]
i dont have experience with that but looks to be not too hard on tutorials,
probably easier to understand than the current code. you can change the
methods in ContactLab.java to room calls...
